### ISSUE TITLE
Spring 2021 workshops are missing materials

### ISSUE THREAD

**Issue by wymcg** [psuieee/projects2020#3]
Certain workshops in the spring2021 folder are missing materials in their respective workshop folders. Listed below are the known gaps:

<ins>Missing Files</ins>
- [ ] 4-plutosdr presentation materials
- [ ] 5-amplifier schematic

<ins>Missing about section</ins>
- [ ] 4-plutosdr 

<ins>Missing required tool lists</ins>
- [ ] 4-plutosdr 
- [ ] 5-amplifier

<ins>Missing parts list</ins>
- [ ] 2-macropad
- [ ] 3-micropython
- [ ] 4-plutosdr 
- [ ] 5-amplifier

<ins>Missing resource links</ins>
- [ ] 3-micropython zoom recording
- [ ] 4-plutosdr recording*

*if available

**Comment by ethantabler** [comment]
PR submitted for fork merge. All Items complete.
