### ISSUE TITLE
Fall 2020 workshops are missing materials

### ISSUE THREAD

**Issue by wymcg** [psuieee/projects2020#7]
Certain workshops in the fall2020 folder are missing materials in their respective workshop folders. Listed below are the known gaps:

<ins>Missing required tool lists</ins>
- [ ] 1-voltagedivider
- [ ] 2-adc
- [ ] 3-pcbdesign
- [ ] 4-matlab

<ins>Missing parts list</ins>
- [ ] 1-voltagedivider
- [ ] 2-adc
- [ ] 3-pcbdesign
- [ ] 4-matlab
- [ ] 5-gui
- [ ] 6-winter

<ins>Missing resource links</ins>
- [ ] 1-voltagedivider
- [ ] 4-matlab

*if available

**Comment by ethantabler** [comment]
PR submitted for fork merge. All Items complete.
